"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['retimed_clips_ui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
  				 'iconfile': 'support/drip.icns',
				 	 'frameworks': ['/usr/lib/libxml2.2.dylib'],
					 'plist': dict(
							CFBundleName="Retimed Clips",
							CFBundleDisplayName="Retimed Clips",
							CFBundlePackageType="APPL",
							FBundleShortVersionString="0.8.0",
							CFBundleVersion="0.8.0",
							NSHumanReadableCopyright="tim@timmoyle.com All rights reserved",
							CFBundleDocumentTypes=[dict(CFBundleTypeExtensions=["xml"],
                                         CFBundleTypeName="XML File",
                                         CFBundleTypeRole="Viewer"),
                                    ],
						),
					}

setup(
    app=APP,
    data_files=DATA_FILES,
    name='Retimed Clips',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
