"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

last_build_id_file = open("support/.last_build_id", "r+")
last_build_id = str(int(last_build_id_file.readline())+1)
last_build_id_file.seek(0, 0)
last_build_id_file.write(last_build_id)
last_build_id_file.close()

APP = ['retimed_clips_ui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
  				 'iconfile': 'support/drip.icns',
				 	 'frameworks': ['/usr/lib/libxml2.2.dylib'],
					 'plist': dict(
							CFBundleName="Retimed Clips",
							CFBundleDisplayName="Retimed Clips",
							CFBundlePackageType="APPL",
							FBundleShortVersionString="0.9.1 %s" % last_build_id,
							CFBundleVersion="0.9.1 build %s" % last_build_id,
							NSHumanReadableCopyright="tim@timmoyle.com All rights reserved",
							CFBundleDocumentTypes=[dict(CFBundleTypeExtensions=["xml"],
                                         CFBundleTypeName="XML File",
                                         CFBundleTypeRole="Viewer"),
                                    ],
						),
					}

setup(
    app=APP,
    data_files=DATA_FILES,
    name='Retimed Clips',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
